// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"time"

	"github.com/google/uuid"
)

type AuthToken struct {
	ID        string        `json:"id"`
	Created   time.Time     `json:"created"`
	Expires   time.Time     `json:"expires"`
	UserID    uuid.NullUUID `json:"user_id"`
	Provider  string        `json:"provider"`
	Verifier  string        `json:"verifier"`
	ReturnUrl string        `json:"return_url"`
}

type Skeleton struct {
	ID      uuid.UUID `json:"id"`
	Created time.Time `json:"created"`
	Updated time.Time `json:"updated"`
	UserID  uuid.UUID `json:"user_id"`
	Name    string    `json:"name"`
	Age     string    `json:"age"`
	Death   time.Time `json:"death"`
	Zombie  bool      `json:"zombie"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	Created    time.Time `json:"created"`
	Updated    time.Time `json:"updated"`
	Email      string    `json:"email"`
	Phone      string    `json:"phone"`
	Access     int64     `json:"access"`
	Sub        string    `json:"sub"`
	Avatar     string    `json:"avatar"`
	ApiKey     string    `json:"api_key"`
	CustomerID string    `json:"customer_id"`
}
