// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredAuthTokens = `-- name: DeleteExpiredAuthTokens :exec
delete from auth_tokens where expires < current_timestamp
`

func (q *Queries) DeleteExpiredAuthTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthTokens)
	return err
}

const deleteSkeleton = `-- name: DeleteSkeleton :exec
delete from skeletons where id = $1 and user_id = $2
`

type DeleteSkeletonParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteSkeleton(ctx context.Context, arg DeleteSkeletonParams) error {
	_, err := q.db.ExecContext(ctx, deleteSkeleton, arg.ID, arg.UserID)
	return err
}

const insertAuthToken = `-- name: InsertAuthToken :one
insert into auth_tokens (id, expires, user_id, provider, verifier, return_url) values ($1, $2, $3, $4, $5, $6) returning id, created, expires, user_id, provider, verifier, return_url
`

type InsertAuthTokenParams struct {
	ID        string        `json:"id"`
	Expires   time.Time     `json:"expires"`
	UserID    uuid.NullUUID `json:"user_id"`
	Provider  string        `json:"provider"`
	Verifier  string        `json:"verifier"`
	ReturnUrl string        `json:"return_url"`
}

func (q *Queries) InsertAuthToken(ctx context.Context, arg InsertAuthTokenParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, insertAuthToken,
		arg.ID,
		arg.Expires,
		arg.UserID,
		arg.Provider,
		arg.Verifier,
		arg.ReturnUrl,
	)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Expires,
		&i.UserID,
		&i.Provider,
		&i.Verifier,
		&i.ReturnUrl,
	)
	return i, err
}

const insertSkeleton = `-- name: InsertSkeleton :one
insert into skeletons (user_id, name, age, death, zombie) values ($1, $2, $3, $4, $5) returning id, created, updated, user_id, name, age, death, zombie
`

type InsertSkeletonParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Age    string    `json:"age"`
	Death  time.Time `json:"death"`
	Zombie bool      `json:"zombie"`
}

func (q *Queries) InsertSkeleton(ctx context.Context, arg InsertSkeletonParams) (Skeleton, error) {
	row := q.db.QueryRowContext(ctx, insertSkeleton,
		arg.UserID,
		arg.Name,
		arg.Age,
		arg.Death,
		arg.Zombie,
	)
	var i Skeleton
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.Name,
		&i.Age,
		&i.Death,
		&i.Zombie,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
insert into users (email, access, sub, avatar, api_key) values ($1, $2, $3, $4, $5) returning id, created, updated, email, phone, access, sub, avatar, api_key, customer_id
`

type InsertUserParams struct {
	Email  string `json:"email"`
	Access int64  `json:"access"`
	Sub    string `json:"sub"`
	Avatar string `json:"avatar"`
	ApiKey string `json:"api_key"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.Email,
		arg.Access,
		arg.Sub,
		arg.Avatar,
		arg.ApiKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.ApiKey,
		&i.CustomerID,
	)
	return i, err
}

const ping = `-- name: Ping :one
select 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const selectAllSkeletons = `-- name: SelectAllSkeletons :many

select id, created, updated, user_id, name, age, death, zombie from skeletons where user_id = $1 order by created desc
`

// Skeletons --
func (q *Queries) SelectAllSkeletons(ctx context.Context, userID uuid.UUID) ([]Skeleton, error) {
	rows, err := q.db.QueryContext(ctx, selectAllSkeletons, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skeleton
	for rows.Next() {
		var i Skeleton
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.UserID,
			&i.Name,
			&i.Age,
			&i.Death,
			&i.Zombie,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAllUsers = `-- name: SelectAllUsers :many

select id, created, updated, email, phone, access, sub, avatar, api_key, customer_id from users
`

// Users --
func (q *Queries) SelectAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, selectAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Created,
			&i.Updated,
			&i.Email,
			&i.Phone,
			&i.Access,
			&i.Sub,
			&i.Avatar,
			&i.ApiKey,
			&i.CustomerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAuthTokenByID = `-- name: SelectAuthTokenByID :one

select id, created, expires, user_id, provider, verifier, return_url from auth_tokens where id = $1
`

// Auth Tokens --
func (q *Queries) SelectAuthTokenByID(ctx context.Context, id string) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, selectAuthTokenByID, id)
	var i AuthToken
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Expires,
		&i.UserID,
		&i.Provider,
		&i.Verifier,
		&i.ReturnUrl,
	)
	return i, err
}

const selectSkeletonByID = `-- name: SelectSkeletonByID :one
select id, created, updated, user_id, name, age, death, zombie from skeletons where id = $1 and user_id = $2
`

type SelectSkeletonByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SelectSkeletonByID(ctx context.Context, arg SelectSkeletonByIDParams) (Skeleton, error) {
	row := q.db.QueryRowContext(ctx, selectSkeletonByID, arg.ID, arg.UserID)
	var i Skeleton
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.Name,
		&i.Age,
		&i.Death,
		&i.Zombie,
	)
	return i, err
}

const selectUserByCustomerID = `-- name: SelectUserByCustomerID :one
select id, created, updated, email, phone, access, sub, avatar, api_key, customer_id from users where customer_id = $1
`

func (q *Queries) SelectUserByCustomerID(ctx context.Context, customerID string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByCustomerID, customerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.ApiKey,
		&i.CustomerID,
	)
	return i, err
}

const selectUserByEmailAndSub = `-- name: SelectUserByEmailAndSub :one
select id, created, updated, email, phone, access, sub, avatar, api_key, customer_id from users where email = $1 and sub = $2
`

type SelectUserByEmailAndSubParams struct {
	Email string `json:"email"`
	Sub   string `json:"sub"`
}

func (q *Queries) SelectUserByEmailAndSub(ctx context.Context, arg SelectUserByEmailAndSubParams) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByEmailAndSub, arg.Email, arg.Sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.ApiKey,
		&i.CustomerID,
	)
	return i, err
}

const selectUserByID = `-- name: SelectUserByID :one
select id, created, updated, email, phone, access, sub, avatar, api_key, customer_id from users where id = $1
`

func (q *Queries) SelectUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.ApiKey,
		&i.CustomerID,
	)
	return i, err
}

const updateAuthToken = `-- name: UpdateAuthToken :exec
update auth_tokens set expires = $1 where id = $2
`

type UpdateAuthTokenParams struct {
	Expires time.Time `json:"expires"`
	ID      string    `json:"id"`
}

func (q *Queries) UpdateAuthToken(ctx context.Context, arg UpdateAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthToken, arg.Expires, arg.ID)
	return err
}

const updateSkeleton = `-- name: UpdateSkeleton :one
update skeletons set 
    name = $1,
    age = $2,
    death = $3,
    zombie = $4,
    updated = current_timestamp
where id = $5 and user_id = $6 returning id, created, updated, user_id, name, age, death, zombie
`

type UpdateSkeletonParams struct {
	Name   string    `json:"name"`
	Age    string    `json:"age"`
	Death  time.Time `json:"death"`
	Zombie bool      `json:"zombie"`
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateSkeleton(ctx context.Context, arg UpdateSkeletonParams) (Skeleton, error) {
	row := q.db.QueryRowContext(ctx, updateSkeleton,
		arg.Name,
		arg.Age,
		arg.Death,
		arg.Zombie,
		arg.ID,
		arg.UserID,
	)
	var i Skeleton
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.UserID,
		&i.Name,
		&i.Age,
		&i.Death,
		&i.Zombie,
	)
	return i, err
}

const updateUserAccess = `-- name: UpdateUserAccess :one
update users set access = $1 where id = $2 returning id, created, updated, email, phone, access, sub, avatar, api_key, customer_id
`

type UpdateUserAccessParams struct {
	Access int64     `json:"access"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserAccess(ctx context.Context, arg UpdateUserAccessParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAccess, arg.Access, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Updated,
		&i.Email,
		&i.Phone,
		&i.Access,
		&i.Sub,
		&i.Avatar,
		&i.ApiKey,
		&i.CustomerID,
	)
	return i, err
}

const updateUserActivity = `-- name: UpdateUserActivity :exec
update users set updated = current_timestamp where id = $1
`

func (q *Queries) UpdateUserActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserActivity, id)
	return err
}

const updateUserCustomerID = `-- name: UpdateUserCustomerID :exec
update users set customer_id = $1 where id = $2
`

type UpdateUserCustomerIDParams struct {
	CustomerID string    `json:"customer_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserCustomerID(ctx context.Context, arg UpdateUserCustomerIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCustomerID, arg.CustomerID, arg.ID)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
update users set phone = $2 where id = $1
`

type UpdateUserPhoneParams struct {
	ID    uuid.UUID `json:"id"`
	Phone string    `json:"phone"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPhone, arg.ID, arg.Phone)
	return err
}
