name: Migration

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  goose-migration:
    name: Run Database Migrations
    runs-on: ubuntu-latest
    environment: ${{ github.event.release.prerelease == true && 'staging' || 'production' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Download Cloud SQL Auth Proxy
        run: |
          wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.18.0/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
          chmod +x cloud-sql-proxy

      - name: Start Cloud SQL Auth Proxy
        run: |
          echo "Starting Cloud SQL Auth Proxy..."
          ./cloud-sql-proxy --address 127.0.0.1 --port 5432 ${{ vars.CLOUD_SQL_CONNECTION_NAME }} &
          PROXY_PID=$!
          echo "PROXY_PID=$PROXY_PID" >> $GITHUB_ENV
          echo "Waiting for proxy to be ready..."
          sleep 5
          if ! kill -0 $PROXY_PID; then echo "Proxy failed to start."; exit 1; fi
          echo "Cloud SQL Auth Proxy ready."

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: false

      - name: Cache Goose binary
        id: cache-goose
        uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-goose

      - name: Setup Goose
        if: steps.cache-goose.outputs.cache-hit != 'true'
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run Migrations
        run: |
          goose -dir ./${{ inputs.directory }}/migrations postgres "user=${{ secrets.DB_USER }} password=${{ secrets.DB_PASSWORD }} host=127.0.0.1 port=5432 dbname=${{ secrets.DB_NAME }} sslmode=disable" up

      - name: Cleanup Port Forwarding
        if: always()
        run: |
          if [ -n "$PROXY_PID" ]; then
            kill $PROXY_PID || true
          fi
